models:
  qwen3-coder-480b-a35b-instruct@doubao:
    api_url: https://dashscope.aliyuncs.com/compatible-mode/v1
    api_key: DASHSCOPE_API_KEY
    request_overrides:
      temperature: 0.1

  deepseek-chat@deepseek:
    api_url: https://api.deepseek.com
    api_key: DEEPSEEK_API_KEY
